sections:
  main:
    display: Main
    fields:
      hero__section:
        type: section
        display: Hero
      hero__partial:
        fieldset: partial__hero
        type: partial
        display: Hero
      sections__section:
        type: section
        display: Sections
      photo_with_content_block__fields:
        child_fieldset: product__partial__photo_with_content_block
        type: accordion_group
        display: Pillars
      abodu_450__fields:
        child_fieldset: product__partial__aobdu_450
        type: accordion_group
        display: 'Abodu 450'
      exterior__fields:
        child_fieldset: product__partial__exterior
        type: accordion_group
        display: Exterior
      two_column_content_grid__fields:
        child_fieldset: product__partial__two_column_content_grid
        type: accordion_group
        display: Interior
      image_grid_with_color_block__fields:
        child_fieldset: product__partial__image_grid_with_color_block
        type: accordion_group
        display: Customize
      design_partnership__photo_with_content_block__fields:
        child_fieldset: product__partial__design_partnership__photo_with_content_block
        type: accordion_group
        display: 'Design Partnership'
      cta__fields:
        child_fieldset: partial__cta
        type: accordion_group
        display: CTA
      is_hidden:
        type: toggle
        display: 'Is Hidden'
        default: 'false'
taxonomies: false
title: 'Product: Page'
