sections:
  main:
    display: Main
    fields:
      slider__fields:
        fieldset: partial__slider
        type: partial
        display: Slider
      content_block_with_pattern__fields:
        fieldset: partial__content_block_with_pattern
        type: partial
        display: 'Content Block with Pattern'
taxonomies: true
title: 'Product: Partial: Abodu 450'
