sections:
  main:
    display: Main
    fields:
      hero__partial:
        fieldset: partial__hero
        type: partial
        display: 'Hero Partial'
      sections__section:
        type: section
        display: Sections
      accordian__fields:
        child_fieldset: service__partial__installation
        type: accordion_group
        display: Installation
      calendar__fields:
        child_fieldset: service_partial_calendar
        type: accordion_group
        display: Calendar
      card_slider__fields:
        type: accordion_group
        display: Timeline
        child_fieldset: service__partial__timeline
      cta__fields:
        child_fieldset: partial__cta
        type: accordion_group
        display: 'Call to Action'
taxonomies: true
title: 'Service: Page'
